POST http://localhost:3000/api/diaries
Content-Type: application/json

{
  "date": "2025-02-26",
  "weather": "sunny",
  "visibility": "splendid",
  "comment": "soaring at great heights in the mountains"
}